// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using enso_Certamen.Models;

#nullable disable

namespace enso_Certamen.Migrations
{
    [DbContext(typeof(boletinLayonContext))]
    [Migration("20251020232451_MakeSubsAndCommentsNullable_v2")]
    partial class MakeSubsAndCommentsNullable_v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("enso_Certamen.Models.boletinGeneral", b =>
                {
                    b.Property<Guid>("GuidBoletin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("DescripcionBoletin")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateOnly>("FechaBoletin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<Guid?>("GuidNoticia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TituloBoletin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("GuidBoletin");

                    b.HasIndex("GuidNoticia");

                    b.ToTable("boletinGeneral");
                });

            modelBuilder.Entity("enso_Certamen.Models.comentarioGeneral", b =>
                {
                    b.Property<Guid>("GuidComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("GuidNoticia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("contenidoComentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("emailLectorComentario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("fechaComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("nombrelectorComentario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("GuidComentario");

                    b.HasIndex("GuidNoticia");

                    b.ToTable("comentarioGeneral");
                });

            modelBuilder.Entity("enso_Certamen.Models.noticiaGeneral", b =>
                {
                    b.Property<Guid>("GuidNoticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("GuidUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("contenidoNoticia")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaNoticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("resumenNoticia")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("tituloNoticia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("GuidNoticia");

                    b.HasIndex("GuidUsuario");

                    b.ToTable("noticiaGeneral");
                });

            modelBuilder.Entity("enso_Certamen.Models.rolGeneral", b =>
                {
                    b.Property<Guid>("GuidRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("descripRol")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("nombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("GuidRol");

                    b.ToTable("rolGeneral");
                });

            modelBuilder.Entity("enso_Certamen.Models.suscripcionGeneral", b =>
                {
                    b.Property<Guid>("GuidSuscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("GuidBoletin")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("emailSuscripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaSuscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("nombreSuscripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuidSuscripcion");

                    b.HasIndex("GuidBoletin");

                    b.ToTable("suscripcionGeneral");
                });

            modelBuilder.Entity("enso_Certamen.Models.usuariosGeneral", b =>
                {
                    b.Property<Guid>("GuidUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("GuidRol")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("apellidoUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("contraUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("emailUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nombreUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("GuidUsuario");

                    b.HasIndex("GuidRol");

                    b.ToTable("usuariosGeneral");
                });

            modelBuilder.Entity("enso_Certamen.Models.boletinGeneral", b =>
                {
                    b.HasOne("enso_Certamen.Models.noticiaGeneral", "GuidNoticiaNavigation")
                        .WithMany("boletinGenerals")
                        .HasForeignKey("GuidNoticia")
                        .HasConstraintName("FK_boletinGeneral_Noticia");

                    b.Navigation("GuidNoticiaNavigation");
                });

            modelBuilder.Entity("enso_Certamen.Models.comentarioGeneral", b =>
                {
                    b.HasOne("enso_Certamen.Models.noticiaGeneral", "GuidNoticiaNavigation")
                        .WithMany("comentarioGenerals")
                        .HasForeignKey("GuidNoticia")
                        .HasConstraintName("FK_comentarioGeneral_Noticia");

                    b.Navigation("GuidNoticiaNavigation");
                });

            modelBuilder.Entity("enso_Certamen.Models.noticiaGeneral", b =>
                {
                    b.HasOne("enso_Certamen.Models.usuariosGeneral", "GuidUsuarioNavigation")
                        .WithMany("noticiaGenerals")
                        .HasForeignKey("GuidUsuario")
                        .HasConstraintName("FK_noticiaGeneral_Usuario");

                    b.Navigation("GuidUsuarioNavigation");
                });

            modelBuilder.Entity("enso_Certamen.Models.suscripcionGeneral", b =>
                {
                    b.HasOne("enso_Certamen.Models.boletinGeneral", "GuidBoletinNavigation")
                        .WithMany("suscripcionGenerals")
                        .HasForeignKey("GuidBoletin")
                        .HasConstraintName("FK_suscripcionGeneral_Boletin");

                    b.Navigation("GuidBoletinNavigation");
                });

            modelBuilder.Entity("enso_Certamen.Models.usuariosGeneral", b =>
                {
                    b.HasOne("enso_Certamen.Models.rolGeneral", "GuidRolNavigation")
                        .WithMany("usuariosGenerals")
                        .HasForeignKey("GuidRol")
                        .HasConstraintName("FK_usuariosGeneral_Rol");

                    b.Navigation("GuidRolNavigation");
                });

            modelBuilder.Entity("enso_Certamen.Models.boletinGeneral", b =>
                {
                    b.Navigation("suscripcionGenerals");
                });

            modelBuilder.Entity("enso_Certamen.Models.noticiaGeneral", b =>
                {
                    b.Navigation("boletinGenerals");

                    b.Navigation("comentarioGenerals");
                });

            modelBuilder.Entity("enso_Certamen.Models.rolGeneral", b =>
                {
                    b.Navigation("usuariosGenerals");
                });

            modelBuilder.Entity("enso_Certamen.Models.usuariosGeneral", b =>
                {
                    b.Navigation("noticiaGenerals");
                });
#pragma warning restore 612, 618
        }
    }
}
